pipeline{
  agent{
    docker{
      image 'python:3.7.2'
      args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
    }
  }
  stages{
    stage('prequisite'){
      steps{
        echo 'check requirement'
        dir('vote'){
          sh 'pip --version'
      }
    }
  }

    stage('build'){
      steps{
        echo 'build stages'
        dir('vote'){
          sh 'pip install -r requirements.txt'
      }
    }
  }

    stage('test'){
      steps{
        echo 'test unit'
//         dir('vote'){
//           sh 'python app.py'
//       }
    }
  }
 
    
}
    post{
      always {
        echo 'Building multibranch pipeline for worker is completed..'
      }
      failure {
          slackSend (channel: "jenkins-cicd", message: "Build Failed Quiz 7.1 (2) by Hadri - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      success {
          slackSend (channel: "jenkins-cicd", message: "Build Succeeded Quiz 7.1 (2) by Hadri - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
    }

  }