pipeline{
agent any
environment {
//  imagename = "khaerulanam/vote"
//  registryCredential = 'dockerlogin'
  workerImage = ''
 }
  
  stages{
     stage('prequisite'){
         agent{
           docker{
           image 'python:3.7.2'
           args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
           }
         }
       steps{
        echo 'check requirement'
        dir('vote'){
          sh 'pip --version'
      }
    }
  }

    stage('build'){
         agent{
           docker{
           image 'python:3.7.2'
           args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
           }
         }
      steps{
        echo 'build stages'
        dir('vote'){
          sh 'pip install -r requirements.txt'
      }
    }
  }

    stage('test'){
         agent{
           docker{
           image 'python:3.7.2'
           args '-u root:sudo -v $HOME/workspace/instavote_vote_vote_Jenkinsfile:/instavote_vote_vote_Jenkinsfile'
           }
         }
      steps{
        echo 'test unit'
//         dir('vote'){
//           sh 'python app.py'
//       }
    }
  }
    

    stage('docker-build'){
        agent any
        steps{
            echo 'Packaging worker app with docker'
            script{
                docker.withRegistry('', 'dockerlogin') {
                    workerImage = docker.build("khaerulanam/vote:v${env.BUILD_ID}", "./vote")
                }
            }
        }
    }

    stage('docker-push'){
        agent any
        steps{
            echo 'Packaging worker app with docker'
            script{
                docker.withRegistry('', 'dockerlogin') {
                    workerImage.push()
                    workerImage.push("latest")
                }
            }
        }
    }
      
      
}
    post{
      always {
        echo 'Building multibranch pipeline for worker is completed..'
      }
      failure {
          slackSend (channel: "jenkins-cicd", message: "Build Failed Quiz 8.1 (2) by Hadri - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
      success {
          slackSend (channel: "jenkins-cicd", message: "Build Succeeded Quiz 8.1 (2) by Hadri - ${env.JOB_NAME} ${env.BUILD_NUMBER} (<${env.BUILD_URL}|Open>)")
      }
    }

  }